site_name: TeachingTools

theme:
  name: "material"
  features:
    - toc.integrate
    - content.tabs.link
    - content.code.copy

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Welcome: index.md
  - Contributing: contributing.md
  - License: license.md

repo_url: https://github.com/PhysicsApps/teaching
use_directory_urls: false
exclude_docs: |
  *.py
  requirements.txt

plugins:
- search
- macros
- autorefs
- tags:
    tags_file: index.md
- gen-files:
    scripts:
      - gen_shinylive.py
- blog:
    post_url_format: "{slug}"
    post_readtime: false
    blog_dir: .
    post_dir: "{blog}/apps"
    categories_toc: true
    archive: false
    post_excerpt: required
    draft: true
    categories_allowed:
      - Templates
      - Mathematics
      - Numerics
      - Physics
    pagination_per_page: 5
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
