site_name: Teaching tools and applications

theme:
  name: "material"
  features:
    - toc.integrate

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - About: about.md
  - License: license.md

repo_url: https://github.com/ptuemmler/TeachingTools
use_directory_urls: false
exclude_docs: |
  *.py
  requirements.txt

plugins:
- search
- macros
- autorefs
- tags
- gen-files:
    scripts:
      - gen_shinylive.py  # or any other name or path
- blog:
    post_url_format: "{slug}"
    post_readtime: false
    blog_dir: .
    post_dir: "{blog}/apps"
    categories_toc: true
    archive: false
    post_excerpt: required
    draft: true
    categories_allowed:
      - Templates
      - Mathematics
      - Numerics
      - Physics
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
