site_name: Teaching tools and applications

theme:
  name: "material"
  features:
    - navigation.indexes
nav:
  - Home: index.md
  - About: about.md
  - License: license.md

repo_url: https://github.com/ptuemmler/msft_web_example
use_directory_urls: false
exclude_docs: |
  *.py
  requirements.txt

plugins:
- search
- macros
- autorefs
- blog:
    post_url_format: "{slug}"
    post_readtime: false
    blog_dir: .
    post_dir: "{blog}/apps"
    categories_toc: true
    archive: false
    post_excerpt: required
- tags
- gen-files:
    scripts:
      - gen_shinylive.py  # or any other name or path