authors:
  ptuemmler:
    name: Paul Tuemmler        # Author name
    description: Strong-field nanophysics # Author description
    avatar: https://www.snp.physik.uni-rostock.de/storages/uni-rostock/Alle_MNF/Physik_Starkfeld/pictures/team/dummy.png # Author avatar
    url: https://github.com/ptuemmler