authors:
  ptuemmler:
    name: Paul Tuemmler        # Author name
    description: Strong-field nanophysics # Author description
    avatar: url         # Author avatar
    url: https://github.com/ptuemmler