authors:
  ptuemmler:
    name: Paul Tuemmler        # Author name
    description: Strong-Field Nanophysics # Author description
    avatar: https://www.snp.physik.uni-rostock.de/storages/uni-rostock/Alle_MNF/Physik_Starkfeld/pictures/team/paul_tuemmler.png
    url: https://github.com/ptuemmler
  lseiffert:
    name: Lennart Seiffert        # Author name
    description: Strong-Field Nanophysics # Author description
    avatar: https://www.snp.physik.uni-rostock.de/storages/uni-rostock/Alle_MNF/Physik_Starkfeld/pictures/team/lennart_seiffert.png
    url: https://github.com/LennartSeiffert
  aherzig:
    name: Anne Herzig        # Author name
    description: Strong-Field Nanophysics # Author description
    avatar: https://www.mathnat.uni-rostock.de/storages/uni-rostock/_processed_/9/3/csm_IfPH_Herzig-Foto_9b3b6cb677.jpg
    url: https://github.com/anneherzig
