authors:
  ptuemmler:
    name: Paul Tuemmler        # Author name
    description: Strong-field nanophysics # Author description
    avatar: https://github.com/ptuemmler.png
    url: https://github.com/ptuemmler